
Trainer:
  accelerator: gpu
  devices: 1
  max_epochs: 3
  val_check_interval: 4000
  accumulate_grad_batches: 4    # batch_size = 8, 8 * 4 = 32
  gradient_clip_val: 1.0
  log_every_n_steps: 50


Callbacks:
  LearningRateMonitor:
    logging_interval: step

  ModelCheckpoint:
    monitor: val_rouge1
    mode: max
    save_top_k: 5
    save_last: True
    dirpath: checkpoints/${now:%Y-%m-%d}/${now:%H-%M-%S}


Profiler:
  SimpleProfiler:
