hydra:
  run:
    dir: ./log/hydra/${now:%Y-%m-%d}/${now:%H-%M-%S}

defaults:
  - _self_
  - dataset: cnn_dm
  - trainer: default

mode:
  dataset: cnn_dm
  model: colo_bert

# BERTSUM checkpoint is required for training CoLo + BERT
model_checkpoint: checkpoints/cnn_dm/bert_base/bertsum.ckpt
train_checkpoint:
test_checkpoint:

model:
  base_checkpoint: bert-base-uncased
  num_ext_sent: 5
  num_can_sent: [2, 3]
  enc_num_layers: 0
  enc_dropout_prob: 0.1
  margin: 0.01
  alpha: 1.0
  beta: 1.0

max_seq_len: 512
batch_size: 16

engine:
  num_can: 5
  n_block: 3
  freeze_base: False
  lr: 1e-3
  betas: [0.9, 0.999]
  num_warmup_steps: 10000
  save_result: True

log:
  project: OrderSum--${mode.dataset}
  name: colo_bert--${now:%Y-%m-%d}/${now:%H-%M-%S}
  save_dir: ./log
