hydra:
  run:
    dir: ./log/hydra/${now:%Y-%m-%d}/${now:%H-%M-%S}

defaults:
  - _self_
  - dataset: wikihow
  - trainer: default

mode:
  dataset: wikihow
  model: bartsum

model_checkpoint:
train_checkpoint:
test_checkpoint:

model:
  base_checkpoint: facebook/bart-large
  enc_num_layers: 0
  enc_dropout_prob: 0.1

max_seq_len: 512
batch_size: 8

engine:
  sum_size: 5
  n_block: 3
  freeze_base: False
  lr: 2e-3
  betas: [0.9, 0.999]
  num_warmup_steps: 10000
  save_result: True

log:
  project: OrderSum--${mode.dataset}
  name: bartsum--${now:%Y-%m-%d}/${now:%H-%M-%S}
  save_dir: ./log
